apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  namespace: default-app
  annotations:
    # Optional: Limits request rate to prevent abuse (DDoS protection)
    traefik.ingress.kubernetes.io/router.middlewares: default-app-ratelimit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: aiops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-service
            port:
              number: 80
